repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # run ruff linting on all files
      - id: ruff
        files: .*

      # run ruff formatting on all files
      - id: ruff-format
        files: .*

  -   repo: https://github.com/pypa/pip-audit
      rev: 'v2.7.3'
      hooks:
        -   id: pip-audit